test: &default

  # Credentials for REST APIs
  client_id: AQ6InSOWuhVbSNVapkCk8KLwK5QLy9gODUZwJocV4OjsER_sjmhvj5B0yH8zQ_ObDuxuhsXJj8mskBpu
  client_secret: EDD79-6usENBkZ01K-p37h3wZfzbp_lV_z5KV5gSzL5FUohRlwF2fcXaITdQ1xbGbFrZKw93s5YgMJ59


  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: mapakn69-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
